/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'linheng' at '2018/2/16 下午 10:52' with Gradle 3.2.1
 *
 * @author linheng, @date 2018/2/16 下午 10:52
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
